;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  ;MENU NASTAVENI
;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
menu_1
	call LCD_1RADEK
	MOVLW 'M'
	CALL ZAPISD
	MOVLW 'E'
	CALL ZAPISD
	MOVLW 'N'
	CALL ZAPISD
	MOVLW 'U'
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW '1'
	CALL ZAPISD
	MOVLW '/'
	CALL ZAPISD
	MOVLW '2'
	CALL ZAPISD
;;;;;;;;;;;;;;;;;;;;
	call LCD_2RADEK

	MOVLW ' '
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW 'Z'
	CALL ZAPISD
	MOVLW 'P'
	CALL ZAPISD
	MOVLW 'E'
	CALL ZAPISD
	MOVLW 'T'
	CALL ZAPISD
;;;;;;;;;;;;;;;;;;;;
	call LCD_3RADEK
   	MOVLW ' '
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW 'p'
	CALL ZAPISD
	MOVLW 'o'
	CALL ZAPISD
	MOVLW 'd'
	CALL ZAPISD
	MOVLW 's'
	CALL ZAPISD
	MOVLW 'v'
	CALL ZAPISD
	MOVLW 'i'
	CALL ZAPISD
	MOVLW 'c'
	CALL ZAPISD
	MOVLW 'e'
	CALL ZAPISD
	MOVLW 'n'
	CALL ZAPISD
	MOVLW 'i'
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW 'L'
	CALL ZAPISD
	MOVLW 'C'
	CALL ZAPISD
	MOVLW 'D'
	CALL ZAPISD
	
;;;;;;;;;;;;;;;;;;;
	call LCD_4RADEK
 	MOVLW ' '
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW 'p'
	CALL ZAPISD
	MOVLW 'o'
	CALL ZAPISD
	MOVLW 'd'
	CALL ZAPISD
	MOVLW 's'
	CALL ZAPISD
	MOVLW 'v'
	CALL ZAPISD
	MOVLW 'i'
	CALL ZAPISD
	MOVLW 'c'
	CALL ZAPISD
	MOVLW 'e'
	CALL ZAPISD
	MOVLW 'n'
	CALL ZAPISD
	MOVLW 'i'
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW 't'
	CALL ZAPISD
	MOVLW 'l'
	CALL ZAPISD
	;call ZPOZ_1S
	;call ZPOZ_1S
	;call ZPOZ_1S
	;call ZPOZ_1S
	;call ZPOZ_1S
	;call ZPOZ_1S
 	;call SMAZ_LCD
	return
;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
menu_2
    call LCD_1RADEK
 	MOVLW 'M'
	CALL ZAPISD
	MOVLW 'E'
	CALL ZAPISD
	MOVLW 'N'
	CALL ZAPISD
	MOVLW 'U'
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW '2'
	CALL ZAPISD
	MOVLW '/'
	CALL ZAPISD
	MOVLW '2'
	CALL ZAPISD
;;;;;;;;;;;;;;;;;;;
	call LCD_2RADEK
 	MOVLW ' '
	CALL ZAPISD
    MOVLW ' '
	CALL ZAPISD	
    MOVLW 'v'
	CALL ZAPISD
	MOVLW 'y'
	CALL ZAPISD
	MOVLW 'v'
	CALL ZAPISD
	MOVLW 'a'
	CALL ZAPISD
	MOVLW 'z'
	CALL ZAPISD
	MOVLW 'e'
	CALL ZAPISD
	MOVLW 'n'
	CALL ZAPISD
	MOVLW 'i'
	CALL ZAPISD
;;;;;;;;;;;;;;;;;;;;;;;
	call LCD_3RADEK
 	MOVLW ' '
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW 'b'
	CALL ZAPISD
	MOVLW 'a'
	CALL ZAPISD
	MOVLW 's'
	CALL ZAPISD
	MOVLW 'y'
	CALL ZAPISD
	call ZPOZ_1S
	call ZPOZ_1S
	call ZPOZ_1S
	call ZPOZ_1S
	call ZPOZ_1S
	call ZPOZ_1S
	call SMAZ_LCD

;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          ;PROCEDURY PRO OBSLUHU ZALOZEK V MENU
;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
podsviceni_LCD
	btfss LCD_PODSVICENI
	goto  $+2
	bcf	  LCD_PODSVICENI	
	;;
	call  LCD_3RADEK
	MOVLW ' '
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW 'p'
	CALL ZAPISD
	MOVLW 'o'
	CALL ZAPISD
	MOVLW 'd'
	CALL ZAPISD
	MOVLW 's'
	CALL ZAPISD
	MOVLW 'v'
	CALL ZAPISD
	MOVLW 'i'
	CALL ZAPISD
	MOVLW 'c'
	CALL ZAPISD
	MOVLW 'e'
	CALL ZAPISD
	MOVLW 'n'
	CALL ZAPISD
	MOVLW 'i'
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW 'L'
	CALL ZAPISD
	MOVLW 'C'
	CALL ZAPISD
	MOVLW 'D'
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD	
	MOVLW 'O'
	CALL ZAPISD
	MOVLW 'F'
	CALL ZAPISD
	MOVLW 'F'
    CALL ZAPISD
	;;
	return
	bsf	  LCD_PODSVICENI
	;;
	call  LCD_3RADEK
	MOVLW ' '
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW 'p'
	CALL ZAPISD
	MOVLW 'o'
	CALL ZAPISD
	MOVLW 'd'
	CALL ZAPISD
	MOVLW 's'
	CALL ZAPISD
	MOVLW 'v'
	CALL ZAPISD
	MOVLW 'i'
	CALL ZAPISD
	MOVLW 'c'
	CALL ZAPISD
	MOVLW 'e'
	CALL ZAPISD
	MOVLW 'n'
	CALL ZAPISD
	MOVLW 'i'
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW 'L'
	CALL ZAPISD
	MOVLW 'C'
	CALL ZAPISD
	MOVLW 'D'
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD	
	MOVLW 'O'
	CALL ZAPISD
	MOVLW 'N'
	CALL ZAPISD
	MOVLW ' '
    CALL ZAPISD
	;;
	return


;;;;;;;;;;;;;;;;;;
podsviceni_TL
	btfss TL_PODSVICENI
	goto  $+2
	bcf	  TL_PODSVICENI
    ;;
    call LCD_4RADEK
 	MOVLW ' '
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW 'p'
	CALL ZAPISD
	MOVLW 'o'
	CALL ZAPISD
	MOVLW 'd'
	CALL ZAPISD
	MOVLW 's'
	CALL ZAPISD
	MOVLW 'v'
	CALL ZAPISD
	MOVLW 'i'
	CALL ZAPISD
	MOVLW 'c'
	CALL ZAPISD
	MOVLW 'e'
	CALL ZAPISD
	MOVLW 'n'
	CALL ZAPISD
	MOVLW 'i'
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW 't'
	CALL ZAPISD
	MOVLW 'l'
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW 'O'
	CALL ZAPISD
	MOVLW 'F'
	CALL ZAPISD
	MOVLW 'F'
	CALL ZAPISD
	;;
	return
	bsf	  TL_PODSVICENI
	;;
	call LCD_4RADEK
 	MOVLW ' '
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW 'p'
	CALL ZAPISD
	MOVLW 'o'
	CALL ZAPISD
	MOVLW 'd'
	CALL ZAPISD
	MOVLW 's'
	CALL ZAPISD
	MOVLW 'v'
	CALL ZAPISD
	MOVLW 'i'
	CALL ZAPISD
	MOVLW 'c'
	CALL ZAPISD
	MOVLW 'e'
	CALL ZAPISD
	MOVLW 'n'
	CALL ZAPISD
	MOVLW 'i'
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW 't'
	CALL ZAPISD
	MOVLW 'l'
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW ' '
	CALL ZAPISD
	MOVLW 'O'
	CALL ZAPISD
	MOVLW 'N' 
	CALL ZAPISD
	return

;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  ;MENU pohyb
;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
sipka_1                 ;sipka na druhem radku menu1
  call menu_1
  call LCD_2RADEK
  MOVLW '>'
  CALL ZAPISD
  return

sipka_2                 ;sipka na tretim radku menu1
  call menu_1
  call LCD_3RADEK
  MOVLW '>'
  CALL ZAPISD
  return

sipka_4                ;sipka na druhem radku menu2
  call menu_2
  call LCD_2RADEK
  MOVLW '>'
  CALL ZAPISD
  return
sipka_3                ;sipka na ctvrtem radku menu1
  call menu_1
  call LCD_4RADEK
  MOVLW '>'
  CALL ZAPISD
  return

sipka_04                ;sipka na druhem radku menu2
  call menu_2
  call LCD_2RADEK
  MOVLW '>'
  CALL ZAPISD
  return

sipka_5                ;sipka na tretim radku menu2
  call menu_2
  call LCD_3RADEK
  MOVLW '>'
  CALL ZAPISD
  return
;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
